// Game nickname policy. Add whole phrases here; avoid broad words such as
// “中国”, “自由”, surnames, or short pinyin fragments that also occur in normal names.
// Traditional forms are folded by name-policy.ts; aliases must be listed explicitly.
export const BLOCKED_NAME_FRAGMENTS = [
  "习近平",
  "习主席",
  "xijinping",
  "毛泽东",
  "毛主席",
  "maozedong",
  "maotsetung",
  "邓小平",
  "dengxiaoping",
  "江泽民",
  "jiangzemin",
  "胡锦涛",
  "hujintao",
  "周恩来",
  "zhouenlai",
  "李克强",
  "likeqiang",
  "赵紫阳",
  "zhaoziyang",
  "蒋介石",
  "jiangjieshi",
  "chiangkaishek",
  "蒋经国",
  "jiangjingguo",
  "蔡英文",
  "tsaiingwen",
  "赖清德",
  "laichingte",
  "共产党",
  "共産党",
  "国民党",
  "民进党",
  "民主进步党",
  "法轮功",
  "法轮大法",
  "falungong",
  "falundafa",
  "天安门事件",
  "天安门屠杀",
  "六四事件",
  "六四屠杀",
  "八九六四",
  "台独",
  "台湾独立",
  "港独",
  "香港独立",
  "藏独",
  "西藏独立",
  "疆独",
  "新疆独立",
  "东突厥斯坦",
  "打倒中共",
  "推翻中共",
  "光复香港",
  "时代革命",
  "希特勒",
  "hitler",
  "纳粹",
] as const;

// Short abbreviations / dates are whole-name matches, so e.g. a normal name
// containing “64” or “dpp” is not accidentally rejected.
export const BLOCKED_EXACT_NAMES = [
  "ccp",
  "cpc",
  "kmt",
  "dpp",
  "nazi",
  "8964",
  "19890604",
  "六四",
] as const;
